using DataToolkit.Library;
using DataToolkit.MigrationBuilder.Configuration;
using DataToolkit.MigrationBuilder.Helpers;
using Microsoft.Extensions.Options;

namespace DataToolkit.MigrationBuilder.Services.Migration;

public sealed class MigrationDdlGeneratorService
{

    private readonly MigrationOptions _options;

    public MigrationDdlGeneratorService(
        IOptions<MigrationOptions> options)
    {
        _options = options.Value;
    }

    public async Task GenerateDdlScriptsAsync(
        List<TableMetadata> metadataSource,
        List<TableMetadata> metadataTarget,
        ArtifactType artifactType)
    {
        Directory.CreateDirectory(
            _options.SqlOutputPath);

        //metadataSource = NormalizeMetadata(metadataSource);
        //metadataTarget = NormalizeMetadata(metadataTarget);

        foreach (TableMetadata sourceTable in metadataSource)
        {
            TableMetadata? targetTable =
                metadataTarget.FirstOrDefault(t =>
                    t.Schema.Equals(
                        sourceTable.Schema,
                        StringComparison.OrdinalIgnoreCase)
                    &&
                    t.Name.Equals(
                        sourceTable.Name,
                        StringComparison.OrdinalIgnoreCase));

            if (targetTable is null)
                continue;

            string ddl = BuildCreateTable(sourceTable, targetTable, artifactType);

            string artifactName =
                artifactType == ArtifactType.WorkFile
                    ? "WF"
                    : "STG";

            string fileName =
                $"DDL_{sourceTable.Schema}.{artifactName}_{sourceTable.Name}.sql";

            string filePath =
                Path.Combine(
                    _options.SqlOutputPath,
                    fileName);

            await File.WriteAllTextAsync(
                filePath,
                ddl);
        }
    }

    private static List<TableMetadata> NormalizeMetadata(
        IEnumerable<TableMetadata> metadata)
    {
        return metadata
            .GroupBy(
                x => $"{x.Schema}.{x.Name}",
                StringComparer.OrdinalIgnoreCase)
            .Select(group => group.First())
            .ToList();
    }

    private static void NormalizeColumns(
        IEnumerable<TableMetadata> metadata)
    {
        foreach (TableMetadata table in metadata)
        {
            table.Columns = table.Columns
                .GroupBy(
                    x => x.Name,
                    StringComparer.OrdinalIgnoreCase)
                .Select(x => x.First())
                .ToList();
        }
    }

    private static string BuildCreateTable(
        TableMetadata sourceTable,
        TableMetadata targetTable,
        ArtifactType artifactType)
    {
        string artifactPrefix =
            artifactType == ArtifactType.WorkFile
                ? "WF"
                : "STG";

        List<string> columns = [];

        // El WFile/Homologation utiliza siempre la estructura del destino para garantizar compatibilidad con la carga.
        foreach (ColumnMetadata targetColumn in targetTable.Columns)
        {
            ColumnMetadata? sourceColumn =
                sourceTable.Columns.FirstOrDefault(c =>
                    c.Name.Equals(
                        targetColumn.Name,
                        StringComparison.OrdinalIgnoreCase));

            columns.Add(
                BuildColumn(
                    sourceColumn,
                    targetColumn));
        }

        string columnScript =
            string.Join(
                "," + Environment.NewLine,
                columns);

        return
$"""
/*
====================================================
TABLE : {artifactPrefix}_{sourceTable.Name}
GENERATED BY DataToolkit.MigrationBuilder
- No constraints, No identities, All columns nullable.
====================================================
*/
--DELETE TABLE {sourceTable.Schema}.{sourceTable.Name};
IF OBJECT_ID('{sourceTable.Schema}.{artifactPrefix}_{sourceTable.Name}') IS NOT NULL
BEGIN
    DROP TABLE [{sourceTable.Schema}].[{artifactPrefix}_{sourceTable.Name}];
END
GO
CREATE TABLE [{sourceTable.Schema}].[{artifactPrefix}_{sourceTable.Name}]
(
{columnScript}
);
GO
""";
    }

    private static string BuildColumn(
        ColumnMetadata? sourceColumn,
        ColumnMetadata targetColumn)
    {
        string warning =
            MigrationWarningExtensions.BuildWarning(
                sourceColumn,
                targetColumn);

        return
            $"        [{targetColumn.Name}] {MigrationWarningExtensions.BuildSqlType(targetColumn)} NULL{warning}";
    }

    

}