using DataToolkit.Library;
using DataToolkit.MigrationBuilder.Configuration;
using DataToolkit.MigrationBuilder.Helpers;
using Microsoft.Extensions.Options;

namespace DataToolkit.MigrationBuilder.Services.Migration;

/// <summary>
/// Generates SQL extraction artifacts.
/// WorkFile -> SELECT.
/// Staging -> INSERT.
/// </summary>
public sealed class MigrationExtractionGeneratorService
{
    private readonly MigrationOptions _options;

    public MigrationExtractionGeneratorService(IOptions<MigrationOptions> options)
    {
        _options = options.Value;
    }

    public async Task GenerateExtractionScriptsAsync(
        List<TableMetadata> metadataSource,
        List<TableMetadata> metadataTarget,
        ArtifactType artifactType)
    {
        Directory.CreateDirectory(_options.SqlOutputPath);

        metadataSource = NormalizeColumns(metadataSource);
        metadataTarget = NormalizeColumns(metadataTarget);

        foreach (TableMetadata sourceTable in metadataSource)
        {
            TableMetadata? targetTable = metadataTarget.FirstOrDefault(t =>
                t.Schema.Equals(sourceTable.Schema, StringComparison.OrdinalIgnoreCase) &&
                t.Name.Equals(sourceTable.Name, StringComparison.OrdinalIgnoreCase));

            if (targetTable is null)
                continue;

            string sql = BuildExtractionScript(sourceTable, targetTable, artifactType);

            string prefix = artifactType == ArtifactType.WorkFile ? "WF" : "STG";

            string fileName = $"SQL_{sourceTable.Schema}.{prefix}_{sourceTable.Name}.sql";

            await File.WriteAllTextAsync(
                Path.Combine(_options.SqlOutputPath, fileName),
                sql);
        }
    }

    private static List<TableMetadata> NormalizeColumns(
        IEnumerable<TableMetadata> metadata)
    {
        List<TableMetadata> tables = metadata.ToList();

        foreach (TableMetadata table in tables)
        {
            table.Columns = table.Columns
                .GroupBy(
                    x => x.Name,
                    StringComparer.OrdinalIgnoreCase)
                .Select(x => x.First())
                .ToList();
        }

        return tables;
    }



    private static string BuildExtractionScript(
    TableMetadata sourceTable,
    TableMetadata targetTable,
    ArtifactType artifactType)
    {
        return artifactType switch
        {
            ArtifactType.WorkFile => BuildSelect(artifactType, sourceTable, targetTable),
            ArtifactType.Staging => BuildSelect(artifactType, sourceTable, targetTable),
            _ => throw new NotSupportedException()
        };
    }
    private static string BuildSelect(
        ArtifactType artifactType,
        TableMetadata sourceTable,
        TableMetadata targetTable)
    {
        List<string> selectColumns = [];

        string prefix = artifactType == ArtifactType.WorkFile ? "WF" : "STG";

        foreach (ColumnMetadata targetColumn in targetTable.Columns)
        {
            ColumnMetadata? sourceColumn =
                sourceTable.Columns.FirstOrDefault(c =>
                    c.Name.Equals(
                        targetColumn.Name,
                        StringComparison.OrdinalIgnoreCase));

            selectColumns.Add(
                BuildColumn(
                    sourceColumn,
                    targetColumn));
        }

        string select =
            string.Join(
                "," + Environment.NewLine,
                selectColumns);

        return
    $"""
/*
====================================================
TABLE : {prefix}_{sourceTable.Name}
GENERATED BY DataToolkit.MigrationBuilder
====================================================
*/

SELECT
{select}
FROM [{sourceTable.Schema}].[{sourceTable.Name}];
""";
    }

    /*
    private static string BuildColumn(
        ColumnMetadata? sourceColumn,
        ColumnMetadata targetColumn)
    {
        string expression =
            sourceColumn is not null
                ? $"[{sourceColumn.Name}]"
                : GetDefaultValue(targetColumn);

        string warning =
            MigrationWarningExtensions.BuildWarning(
                sourceColumn,
                targetColumn);

        return
            $"    {expression} AS [{targetColumn.Name}]{warning}";
    }*/
    private static string BuildColumn(
        ColumnMetadata? sourceColumn,
        ColumnMetadata targetColumn)
    {
        string expression;

        if (sourceColumn is not null)
        {
            expression = $"[{sourceColumn.Name}]";

            if (!string.IsNullOrWhiteSpace(sourceColumn.Collation) &&
                !string.IsNullOrWhiteSpace(targetColumn.Collation) &&
                !sourceColumn.Collation.Equals(targetColumn.Collation,
                    StringComparison.OrdinalIgnoreCase))
            {
                expression += $" COLLATE {targetColumn.Collation}";
            }
        }
        else
        {
            expression = GetDefaultValue(targetColumn);
        }

        string warning =
            MigrationWarningExtensions.BuildWarning(
                sourceColumn,
                targetColumn);

        return $"    {expression} AS [{targetColumn.Name}]{warning}";
    }

    private static string GetDefaultValue(ColumnMetadata column)
    {
        // Si acepta NULL, no hay problema.
        //if (column.IsNullable)
        //    return "NULL";

        string dataType = column.SqlType.ToLowerInvariant();

        // Tipos texto
        if (dataType is "char"
            or "varchar"
            or "nchar"
            or "nvarchar"
            or "text"
            or "ntext")
        {
            return "''";
        }

        // Tipos numéricos
        if (dataType is "tinyint"
            or "smallint"
            or "int"
            or "bigint"
            or "decimal"
            or "numeric"
            or "float"
            or "real"
            or "money"
            or "smallmoney")
        {
            return "0";
        }

        // Bits (Sí/No)
        if (dataType == "bit")
        {
            return "0";
        }

        // Fechas
        if (dataType is "date"
            or "datetime"
            or "datetime2"
            or "smalldatetime")
        {
            return "'1900-01-01'";
        }

        // GUID
        if (dataType == "uniqueidentifier")
        {
            return "'00000000-0000-0000-0000-000000000000'";
        }

        // Valor por defecto para tipos desconocidos
        return "NULL";
    }

}
