using DataToolkit.MigrationBuilder.Configuration;
using DataToolkit.MigrationBuilder.Helpers;
using Microsoft.Extensions.Options;

namespace DataToolkit.MigrationBuilder.Services.Migration;

public sealed class MigrationDdlGeneratorService
{

    private readonly MigrationOptions _options;

    public MigrationDdlGeneratorService(
        IOptions<MigrationOptions> options)
    {
        _options = options.Value;
    }

    public async Task GenerateDdlScriptsAsync(
        List<TableMetadata> metadataSource,
        List<TableMetadata> metadataTarget,
        ArtifactType artifactType)
    {
        Directory.CreateDirectory(
            _options.SqlOutputPath);

        foreach (TableMetadata sourceTable in metadataSource)
        {
            TableMetadata? targetTable =
                metadataTarget.FirstOrDefault(t =>
                    t.Schema.Equals(
                        sourceTable.Schema,
                        StringComparison.OrdinalIgnoreCase)
                    &&
                    t.Name.Equals(
                        sourceTable.Name,
                        StringComparison.OrdinalIgnoreCase));

            if (targetTable is null)
                continue;

            string ddl = BuildCreateTable(sourceTable, targetTable, artifactType);

            string artifactName =
                artifactType == ArtifactType.WorkFile
                    ? "WF"
                    : "STG";

            string fileName =
                $"DDL_{sourceTable.Schema}.{artifactName}_{sourceTable.Name}.sql";

            string filePath =
                Path.Combine(
                    _options.SqlOutputPath,
                    fileName);

            await File.WriteAllTextAsync(
                filePath,
                ddl);
        }
    }

    private static string BuildCreateTable(
        TableMetadata sourceTable,
        TableMetadata targetTable,
        ArtifactType artifactType)
    {
        string artifactPrefix =
            artifactType == ArtifactType.WorkFile
                ? "WF"
                : "STG";

        List<string> columns = [];

        // El WFile/Homologation utiliza siempre la estructura del destino para garantizar compatibilidad con la carga.
        foreach (ColumnMetadata targetColumn in targetTable.Columns)
        {
            ColumnMetadata? sourceColumn =
                sourceTable.Columns.FirstOrDefault(c =>
                    c.Name.Equals(
                        targetColumn.Name,
                        StringComparison.OrdinalIgnoreCase));

            columns.Add(
                BuildColumn(
                    sourceColumn,
                    targetColumn));
        }

        string columnScript =
            string.Join(
                "," + Environment.NewLine,
                columns);

        return
$"""
/*
====================================================
TABLE : {artifactPrefix}_{sourceTable.Name}
GENERATED BY DataToolkit.MigrationBuilder
- No constraints, No identities, All columns nullable.
====================================================
*/

IF OBJECT_ID('{sourceTable.Schema}.{artifactPrefix}_{sourceTable.Name}') IS NOT NULL
BEGIN
    DROP TABLE [{sourceTable.Schema}].[{artifactPrefix}_{sourceTable.Name}];
END
GO
CREATE TABLE [{sourceTable.Schema}].[{artifactPrefix}_{sourceTable.Name}]
(
{columnScript}
);
GO
""";
    }

    private static string BuildColumn(
        ColumnMetadata? sourceColumn,
        ColumnMetadata targetColumn)
    {
        string warning =
            BuildWarning(
                sourceColumn,
                targetColumn);

        return
            $"        [{targetColumn.Name}] {BuildSqlType(targetColumn)} NULL{warning}";
    }

    private static string BuildWarning(
        ColumnMetadata? source,
        ColumnMetadata target)
    {
        if (source is null)
            return string.Empty;

        string sourceType = BuildSqlType(source);
        string targetType = BuildSqlType(target);

        // Tipo de dato
        if (!source.SqlType.Equals(
                target.SqlType,
                StringComparison.OrdinalIgnoreCase))
        {
            return
                $" /* WARNING: Source {sourceType} -> Target {targetType}. {MigrationWarning.DataTypeMismatch.GetMessage()} */";
        }

        // Longitud
        if (int.TryParse(source.MaxLength, out var sourceLength) &&
            int.TryParse(target.MaxLength, out var targetLength) &&
            sourceLength > targetLength)
        {
            return
                $" /* WARNING: Source {sourceType} -> Target {targetType}. {MigrationWarning.LengthMismatch.GetMessage()} */";
        }

        // Precisión
        if (int.TryParse(source.Precision, out var sourcePrecision) &&
            int.TryParse(target.Precision, out var targetPrecision) &&
            sourcePrecision > targetPrecision)
        {
            return
                $" /* WARNING: Source {sourceType} -> Target {targetType}. {MigrationWarning.PrecisionMismatch.GetMessage()} */";
        }

        // Escala
        if (int.TryParse(source.Scale, out var sourceScale) &&
            int.TryParse(target.Scale, out var targetScale) &&
            sourceScale > targetScale)
        {
            return
                $" /* WARNING: Source {sourceType} -> Target {targetType}. {MigrationWarning.ScaleMismatch.GetMessage()} */";
        }

        // Nullable
        if (source.IsNullable && !target.IsNullable)
        {
            return
                $" /* WARNING: Source NULL -> Target NOT NULL. {MigrationWarning.NullableMismatch.GetMessage()} */";
        }

        return string.Empty;
    }

    private static string BuildSqlType(ColumnMetadata column)
    {
        var type = column.SqlType.ToLowerInvariant();

        return type switch
        {
            "char" or "varchar" or "nchar" or "nvarchar"
            or "binary" or "varbinary"
                => string.IsNullOrWhiteSpace(column.MaxLength)
                    ? column.SqlType
                    : $"{column.SqlType}({column.MaxLength})",

            "decimal" or "numeric"
                => string.IsNullOrWhiteSpace(column.Precision) ||
                   string.IsNullOrWhiteSpace(column.Scale)
                    ? column.SqlType
                    : $"{column.SqlType}({column.Precision},{column.Scale})",

            "datetime2" or "datetimeoffset" or "time"
                => string.IsNullOrWhiteSpace(column.Scale)
                    ? column.SqlType
                    : $"{column.SqlType}({column.Scale})",

            _ => column.SqlType
        };
    }


}